### ISSUE TITLE
Right panel header is sometimes displayed with one or two lines

### ISSUE THREAD

**Issue by heytitle** [codeforthailand/past-election-map#33]
For 2562, the header is displayed with two lines
![Screen Shot 2020-04-24 at 4 55 31 PM](https://user-images.githubusercontent.com/1214890/80226333-8548d200-864c-11ea-9e1f-87d55d137d72.png)

For 2554, it is displayed with one line.
![Screen Shot 2020-04-24 at 4 55 36 PM](https://user-images.githubusercontent.com/1214890/80226337-87ab2c00-864c-11ea-9ac9-64aced5cd9c8.png)

IMHO, one line looks better. I guess we can just reduce the font size?

**Comment by rapee** [comment]
I believe this is fixed. Can you confirm? @heytitle

**Comment by heytitle** [comment]
This might be Safari's issue; the header looks ok on Chrome.

My Safari version is 13.0.2.

**Comment by rapee** [comment]
Fixed in 3874a9b
