### ISSUE TITLE
Number in area indicators are displayed slightly off for Bangkok

### ISSUE THREAD

**Issue by heytitle** [codeforthailand/past-election-map#34]
![image](https://user-images.githubusercontent.com/1214890/80226694-fab4a280-864c-11ea-820c-3d78a3ca523b.png)

It seems the numbers are not vertically in the middle; they are slightly towards the top.

On the left panel, the numbers are also hard to read.

![image](https://user-images.githubusercontent.com/1214890/80226916-423b2e80-864d-11ea-96f8-2bbe6e74c501.png)

**Comment by rapee** [comment]
Need investigation. What is your environment (OS, browser)? @heytitle

**Comment by heytitle** [comment]
The screenshots were taken using Safari Version 13.0.2. Interestingly, I don't see the issues on Chrome.

**Comment by rapee** [comment]
@thasarito Can you take a look into this?

**Comment by thasarito** [comment]
look to be safari's issue between dominant-baseline, dy and scale. please check if this commit fixed it kub.

**Comment by heytitle** [comment]
@thasarito thanks for the fix! it looks good now 🍻
