### ISSUE TITLE
Link politician names in the right panel to theyworkforus

### ISSUE THREAD

**Issue by heytitle** [codeforthailand/past-election-map#36]
It would be nice if we link the politician names to their theyworkforus pages.

Moreover, we might consider to display their images here.

![Screen Shot 2020-04-26 at 10 59 22 AM](https://user-images.githubusercontent.com/1214890/80302925-3d8d8c00-87ad-11ea-9f61-12eeaadb1886.png)

**Comment by rapee** [comment]
Fixed in 19452b3
